footprint: [[-0.4, -0.3], [-0.4, 0.3], [0.4, 0.3], [0.4, -0.3]]
footprint_padding: 0.2
robot_base_frame: base_link
update_frequency: 10.0
publish_frequency: 1.0
transform_tolerance: 1.0
publish_voxel_map: false
resolution: 0.05

obstacle_range: 10.0
raytrace_range: 10.5
static:
    map_topic: /map
    subscribe_to_updates: true
    lethal_cost_threshold: 50

no_go_zones:
    map_topic: /map_no_go
    subscribe_to_updates: true
    lethal_cost_threshold: 50

obstacles_laser:
    observation_sources: scan_filtered
    scan_filtered: {data_type: LaserScan, clearing: true, marking: true, topic: scan_filtered, inf_is_valid: false, min_obstacle_height: -1.0}

inflation:
  inflation_radius: 1.0
  cost_scaling_factor: 2.0
