global_frame: map
robot_base_frame: base_link
static_map: true
rolling_window: false
track_unknown_space: false
width: 400
height: 400

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  # - {name: obstacles_laser,         type: "costmap_2d::ObstacleLayer"}
  # - {name: rgbd_obstacle_layer,     type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}


