footprint: [[-0.45, -0.35], [-0.45, 0.35], [0.45, 0.35], [0.45, -0.35]]
footprint_padding: 0.05
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 2.0
transform_tolerance: 1.0
publish_voxel_map: true
resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.1
