global_frame: map
rolling_window: false
track_unknown_space: true
width: 30
height: 30

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
  - {name: obstacles_laser,         type: "costmap_2d::ObstacleLayer"}


