GlobalPlanner:
  cost_factor: 3.0
  lethal_cost: 253
  neutral_cost: 66
  orientation_mode: 1
  publish_potential: true
  use_dijkstra: false


NavfnROS:
  allow_unknown: true
  default_tolerance: 0.1