GlobalPlanner:
  cost_factor: 3.0
  lethal_cost: 253
  neutral_cost: 66
  orientation_mode: 2
  publish_potential: true
  use_dijkstra: true

NavfnROS:
  allow_unknown: true
  default_tolerance: 0.1


SBPLLatticePlanner:
  environment_type: XYThetaLattice
  planner_type: ARAPlanner
  allocated_time: 5.0
  initial_epsilon: 3.0
  forward_search: false