topics:
-
  name    : navigation
  topic   : nav/cmd_vel
  timeout : 0.5
  priority: 50
-
  name    : joystick
  topic   : joy/cmd_vel
  timeout : 0.5
  priority: 100
-
  name    : keyboard
  topic   : keyboard/cmd_vel
  timeout : 0.5
  priority: 90
-
  name    : website
  topic   : website/cmd_vel
  timeout : 0.5
  priority: 60
-
  name    : voice
  topic   : voice/cmd_vel
  timeout : 0.5
  priority: 50
