<?xml version="1.0"?>

<robot name="copernicus" xmlns:xacro="https://ros.org/wiki/xacro">
  <xacro:macro name="lidar" params="frame:=lidar topic:=scan sample_size:=720 update_rate:=50
                 min_angle:=-2.35619 max_angle:=2.35619 min_range:=0.5 max_range:=20.0 robot_namespace:=/copernicus">

      <joint name="laser_joint" type="fixed">
          <!-- This offset is from the base of the bracket to the LIDAR's focal point. -->
          <origin xyz="${chassis_l/2 + 0.052} 0 0" rpy="${PI} 0 0" />
          <parent link="base_link" />
          <child link="${frame}" />
      </joint>
      
      <link name="${frame}">
          <visual>
              <origin/>
              <geometry>
                  <mesh filename="package://copernicus_description/meshes/lms1xx.stl"/>
              </geometry>
              <material name="gray"/>
          </visual>
          <collision>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <geometry>
                <mesh filename="package://copernicus_description/meshes/lms1xx.stl"/>
              </geometry>
          </collision>
          <inertial>
              <origin xyz="0 0 0" rpy="0 0 0"/>
              <mass value="1.1"/>
              <inertia ixx="${0.0833333 * 1.1 * (0.102*0.102 + 0.152*0.152)}" ixy="0.0" ixz="0.0"
          iyy="${0.0833333 * 1.1 * (0.105*0.105 + 0.152*0.152)}" iyz="0.0"
          izz="${0.0833333 * 1.1 * (0.105*0.105 + 0.102*0.102)}" />
          </inertial>
      </link>


      <gazebo reference="${frame}">
        <turnGravityOff>true</turnGravityOff>
        <sensor type="ray" name="${frame}">
          <pose>0 0 0 0 0 0</pose>
          <visualize>false</visualize>
          <update_rate>${update_rate}</update_rate>
          <ray>
            <scan>
              <horizontal>
                <samples>${sample_size}</samples>
                <resolution>1</resolution>
                <min_angle>${min_angle}</min_angle>
                <max_angle>${max_angle}</max_angle>
              </horizontal>
            </scan>
            <range>
              <min>${min_range}</min>
              <max>${max_range}</max>
              <resolution>0.01</resolution>
            </range>
            <noise>
              <type>gaussian</type>
              <mean>0.0</mean>
              <stddev>0.001</stddev>
            </noise>
          </ray>
          <plugin name="gazebo_ros_laser" filename="libgazebo_ros_laser.so">
            <topicName>${topic}</topicName>
            <frameName>${frame}</frameName>
            <robotNamespace>${robot_namespace}</robotNamespace>
          </plugin>
        </sensor>
      </gazebo>
  </xacro:macro>
</robot>