scan_filter_chain:
- name: laser_cutoff
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: -1.57
    upper_angle: 1.57
    # box_frame: lms
    # min_x: -2.0
    # min_y: -2.0
    # min_z: -2.0
    # max_x: 2.0
    # max_y: 2.0
    # max_z: 2.0
