enable_button: 1
stop_button: 2
e_stop_button: 3
linear_speed_axis: 1
angular_speed_axis: 0

max_linear_speed: 0.5
max_angular_speed: 0.5

enable_holonomic_movement: 0
sideways_speed_axis: -1

enable_e_stop: 1

cmd_vel_topic: /joy/cmd_vel
e_stop_pub_topic: /subsPBFlags

e_stop_sub_topic: /PBFlags
joy_topic: /joy